#!/bin/bash
if [ -z $1 ]
  then
    echo "Usage: publish-artifactory <artifactory_url> (e.g. https://example.org/artifactory)"
    exit 1
fi

ARTIFACTORY_URL=$1

sbt -Dsbt.override.publish.repos.release=$ARTIFACTORY_URL/general \
    -Dsbt.override.publish.repos.snapshot=$ARTIFACTORY_URL/general-snapshots \
    "set credentials in Global += Credentials(Path.userHome / \".artifactory_credentials\")" "+publish"
